export const brand = {
  name: "PlacePrep",
  tagline: "AI Placement Readiness",
};

// A curated suggestion list for the skills picker in onboarding. This is just
// autocomplete scaffolding for the UI — actual student data always comes from the API.
export const skillSuggestions = [
  "Python",
  "Java",
  "C++",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Express",
  "Docker",
  "Kubernetes",
  "Linux",
  "AWS",
  "GCP",
  "Azure",
  "Git",
  "GitHub Actions",
  "SQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "GraphQL",
  "REST APIs",
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "Computer Vision",
  "Cybersecurity",
  "System Design",
  "DSA",
  "Tailwind CSS",
  "Figma",
  "Rust",
  "Go",
  "Kafka",
];
