/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRoadmapRouteImport } from './routes/dashboard/roadmap'
import { Route as DashboardResultsRouteImport } from './routes/dashboard/results'
import { Route as DashboardQuizHistoryRouteImport } from './routes/dashboard/quiz-history'
import { Route as DashboardInterviewHistoryRouteImport } from './routes/dashboard/interview-history'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminStudentsIdRouteImport } from './routes/admin/students/$id'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoadmapRoute = DashboardRoadmapRouteImport.update({
  id: '/dashboard/roadmap',
  path: '/dashboard/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResultsRoute = DashboardResultsRouteImport.update({
  id: '/dashboard/results',
  path: '/dashboard/results',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQuizHistoryRoute = DashboardQuizHistoryRouteImport.update({
  id: '/dashboard/quiz-history',
  path: '/dashboard/quiz-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInterviewHistoryRoute =
  DashboardInterviewHistoryRouteImport.update({
    id: '/dashboard/interview-history',
    path: '/dashboard/interview-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/admin/students/',
  path: '/admin/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/admin/students/$id',
  path: '/admin/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/interview': typeof InterviewRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/interview-history': typeof DashboardInterviewHistoryRoute
  '/dashboard/quiz-history': typeof DashboardQuizHistoryRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/interview': typeof InterviewRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/interview-history': typeof DashboardInterviewHistoryRoute
  '/dashboard/quiz-history': typeof DashboardQuizHistoryRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/admin/students': typeof AdminStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/interview': typeof InterviewRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/interview-history': typeof DashboardInterviewHistoryRoute
  '/dashboard/quiz-history': typeof DashboardQuizHistoryRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/interview'
    | '/onboarding'
    | '/quiz'
    | '/results'
    | '/admin/analytics'
    | '/admin/companies'
    | '/admin/roles'
    | '/admin/settings'
    | '/dashboard/interview-history'
    | '/dashboard/quiz-history'
    | '/dashboard/results'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/students/$id'
    | '/admin/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/interview'
    | '/onboarding'
    | '/quiz'
    | '/results'
    | '/admin/analytics'
    | '/admin/companies'
    | '/admin/roles'
    | '/admin/settings'
    | '/dashboard/interview-history'
    | '/dashboard/quiz-history'
    | '/dashboard/results'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/admin/students/$id'
    | '/admin/students'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/interview'
    | '/onboarding'
    | '/quiz'
    | '/results'
    | '/admin/analytics'
    | '/admin/companies'
    | '/admin/roles'
    | '/admin/settings'
    | '/dashboard/interview-history'
    | '/dashboard/quiz-history'
    | '/dashboard/results'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/students/$id'
    | '/admin/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  InterviewRoute: typeof InterviewRoute
  OnboardingRoute: typeof OnboardingRoute
  QuizRoute: typeof QuizRoute
  ResultsRoute: typeof ResultsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  DashboardInterviewHistoryRoute: typeof DashboardInterviewHistoryRoute
  DashboardQuizHistoryRoute: typeof DashboardQuizHistoryRoute
  DashboardResultsRoute: typeof DashboardResultsRoute
  DashboardRoadmapRoute: typeof DashboardRoadmapRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/roadmap': {
      id: '/dashboard/roadmap'
      path: '/dashboard/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof DashboardRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/results': {
      id: '/dashboard/results'
      path: '/dashboard/results'
      fullPath: '/dashboard/results'
      preLoaderRoute: typeof DashboardResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quiz-history': {
      id: '/dashboard/quiz-history'
      path: '/dashboard/quiz-history'
      fullPath: '/dashboard/quiz-history'
      preLoaderRoute: typeof DashboardQuizHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/interview-history': {
      id: '/dashboard/interview-history'
      path: '/dashboard/interview-history'
      fullPath: '/dashboard/interview-history'
      preLoaderRoute: typeof DashboardInterviewHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/admin/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/admin/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  InterviewRoute: InterviewRoute,
  OnboardingRoute: OnboardingRoute,
  QuizRoute: QuizRoute,
  ResultsRoute: ResultsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  DashboardInterviewHistoryRoute: DashboardInterviewHistoryRoute,
  DashboardQuizHistoryRoute: DashboardQuizHistoryRoute,
  DashboardResultsRoute: DashboardResultsRoute,
  DashboardRoadmapRoute: DashboardRoadmapRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminStudentsIdRoute: AdminStudentsIdRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
